version: "3.9"
services:
    database:
        image: postgres:14.5
        restart: always
        environment:
                POSTGRES_USER: admin
                POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"
        volumes:
            - "database:/var/lib/postgresql/data"
    application:
        build:
            context: .
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
        depends_on:
            - database
volumes:
    database:
